variable "enviroment" {}
variable "project" {}
variable "subscriptions" {}
#variable "rg_name" {}
variable "location" {}
variable "tags" {}
variable "address_space" {}
variable "subnets" {}
variable "datalake_sa_name" {}
variable "workspace1_name" {}
variable "workspace1_file_name" {}
variable "workspace1_sql_admin" {}
variable "aad_admin1" {}
variable "workspace1_managed_network" {}
variable "server_name" {}  
variable "admin_username" {}
variable "admin_password" {}
variable "domain_name" {}